name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies and build package
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip setuptools wheel twine
          python setup.py sdist

      - name: Publish to PyPI
        run: |
          source venv/bin/activate
          twine upload --skip-existing dist/*
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
